/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as DiagnosticosRouteImport } from './routes/diagnosticos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SiteRouteImport } from './routes/site'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as AgendarDateRouteImport } from './routes/agendar.$date'
import { Route as DiagnosticosIndexRouteImport } from './routes/diagnosticos.index'
import { Route as DiagnosticosConfiguracoesRouteImport } from './routes/diagnosticos.configuracoes'
import { Route as PdfTokenRouteImport } from './routes/pdf.$token'
import { Route as DiagnosticosClientesClienteIdRouteImport } from './routes/diagnosticos.clientes.$clienteId'
import { Route as DiagnosticosEditorDiagnosticoIdRouteImport } from './routes/diagnosticos.editor.$diagnosticoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosRoute = DiagnosticosRouteImport.update({
  id: '/diagnosticos',
  path: '/diagnosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarDateRoute = AgendarDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => AgendarRoute,
} as any)
const DiagnosticosIndexRoute = DiagnosticosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticosRoute,
} as any)
const DiagnosticosConfiguracoesRoute =
  DiagnosticosConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => DiagnosticosRoute,
  } as any)
const PdfTokenRoute = PdfTokenRouteImport.update({
  id: '/pdf/$token',
  path: '/pdf/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosClientesClienteIdRoute =
  DiagnosticosClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => DiagnosticosRoute,
  } as any)
const DiagnosticosEditorDiagnosticoIdRoute =
  DiagnosticosEditorDiagnosticoIdRouteImport.update({
    id: '/editor/$diagnosticoId',
    path: '/editor/$diagnosticoId',
    getParentRoute: () => DiagnosticosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/atendimentos': typeof AtendimentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/diagnosticos': typeof DiagnosticosRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/site': typeof SiteRoute
  '/usuarios': typeof UsuariosRoute
  '/agendar/$date': typeof AgendarDateRoute
  '/diagnosticos/configuracoes': typeof DiagnosticosConfiguracoesRoute
  '/pdf/$token': typeof PdfTokenRoute
  '/diagnosticos/': typeof DiagnosticosIndexRoute
  '/diagnosticos/clientes/$clienteId': typeof DiagnosticosClientesClienteIdRoute
  '/diagnosticos/editor/$diagnosticoId': typeof DiagnosticosEditorDiagnosticoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/atendimentos': typeof AtendimentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/site': typeof SiteRoute
  '/usuarios': typeof UsuariosRoute
  '/agendar/$date': typeof AgendarDateRoute
  '/diagnosticos/configuracoes': typeof DiagnosticosConfiguracoesRoute
  '/pdf/$token': typeof PdfTokenRoute
  '/diagnosticos': typeof DiagnosticosIndexRoute
  '/diagnosticos/clientes/$clienteId': typeof DiagnosticosClientesClienteIdRoute
  '/diagnosticos/editor/$diagnosticoId': typeof DiagnosticosEditorDiagnosticoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/atendimentos': typeof AtendimentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/diagnosticos': typeof DiagnosticosRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/site': typeof SiteRoute
  '/usuarios': typeof UsuariosRoute
  '/agendar/$date': typeof AgendarDateRoute
  '/diagnosticos/configuracoes': typeof DiagnosticosConfiguracoesRoute
  '/pdf/$token': typeof PdfTokenRoute
  '/diagnosticos/': typeof DiagnosticosIndexRoute
  '/diagnosticos/clientes/$clienteId': typeof DiagnosticosClientesClienteIdRoute
  '/diagnosticos/editor/$diagnosticoId': typeof DiagnosticosEditorDiagnosticoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/atendimentos'
    | '/clientes'
    | '/configuracoes'
    | '/custos'
    | '/diagnosticos'
    | '/login'
    | '/privacidade'
    | '/procedimentos'
    | '/relatorios'
    | '/site'
    | '/usuarios'
    | '/agendar/$date'
    | '/diagnosticos/configuracoes'
    | '/pdf/$token'
    | '/diagnosticos/'
    | '/diagnosticos/clientes/$clienteId'
    | '/diagnosticos/editor/$diagnosticoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/atendimentos'
    | '/clientes'
    | '/configuracoes'
    | '/custos'
    | '/login'
    | '/privacidade'
    | '/procedimentos'
    | '/relatorios'
    | '/site'
    | '/usuarios'
    | '/agendar/$date'
    | '/diagnosticos/configuracoes'
    | '/pdf/$token'
    | '/diagnosticos'
    | '/diagnosticos/clientes/$clienteId'
    | '/diagnosticos/editor/$diagnosticoId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agendar'
    | '/atendimentos'
    | '/clientes'
    | '/configuracoes'
    | '/custos'
    | '/diagnosticos'
    | '/login'
    | '/privacidade'
    | '/procedimentos'
    | '/relatorios'
    | '/site'
    | '/usuarios'
    | '/agendar/$date'
    | '/diagnosticos/configuracoes'
    | '/pdf/$token'
    | '/diagnosticos/'
    | '/diagnosticos/clientes/$clienteId'
    | '/diagnosticos/editor/$diagnosticoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgendarRoute: typeof AgendarRouteWithChildren
  AtendimentosRoute: typeof AtendimentosRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosRoute: typeof CustosRoute
  DiagnosticosRoute: typeof DiagnosticosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SiteRoute: typeof SiteRoute
  UsuariosRoute: typeof UsuariosRoute
  PdfTokenRoute: typeof PdfTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos': {
      id: '/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/diagnosticos'
      preLoaderRoute: typeof DiagnosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$date': {
      id: '/agendar/$date'
      path: '/$date'
      fullPath: '/agendar/$date'
      preLoaderRoute: typeof AgendarDateRouteImport
      parentRoute: typeof AgendarRoute
    }
    '/diagnosticos/': {
      id: '/diagnosticos/'
      path: '/'
      fullPath: '/diagnosticos/'
      preLoaderRoute: typeof DiagnosticosIndexRouteImport
      parentRoute: typeof DiagnosticosRoute
    }
    '/diagnosticos/configuracoes': {
      id: '/diagnosticos/configuracoes'
      path: '/configuracoes'
      fullPath: '/diagnosticos/configuracoes'
      preLoaderRoute: typeof DiagnosticosConfiguracoesRouteImport
      parentRoute: typeof DiagnosticosRoute
    }
    '/pdf/$token': {
      id: '/pdf/$token'
      path: '/pdf/$token'
      fullPath: '/pdf/$token'
      preLoaderRoute: typeof PdfTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos/clientes/$clienteId': {
      id: '/diagnosticos/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/diagnosticos/clientes/$clienteId'
      preLoaderRoute: typeof DiagnosticosClientesClienteIdRouteImport
      parentRoute: typeof DiagnosticosRoute
    }
    '/diagnosticos/editor/$diagnosticoId': {
      id: '/diagnosticos/editor/$diagnosticoId'
      path: '/editor/$diagnosticoId'
      fullPath: '/diagnosticos/editor/$diagnosticoId'
      preLoaderRoute: typeof DiagnosticosEditorDiagnosticoIdRouteImport
      parentRoute: typeof DiagnosticosRoute
    }
  }
}

interface AgendarRouteChildren {
  AgendarDateRoute: typeof AgendarDateRoute
}

const AgendarRouteChildren: AgendarRouteChildren = {
  AgendarDateRoute: AgendarDateRoute,
}

const AgendarRouteWithChildren =
  AgendarRoute._addFileChildren(AgendarRouteChildren)

interface DiagnosticosRouteChildren {
  DiagnosticosConfiguracoesRoute: typeof DiagnosticosConfiguracoesRoute
  DiagnosticosIndexRoute: typeof DiagnosticosIndexRoute
  DiagnosticosClientesClienteIdRoute: typeof DiagnosticosClientesClienteIdRoute
  DiagnosticosEditorDiagnosticoIdRoute: typeof DiagnosticosEditorDiagnosticoIdRoute
}

const DiagnosticosRouteChildren: DiagnosticosRouteChildren = {
  DiagnosticosConfiguracoesRoute: DiagnosticosConfiguracoesRoute,
  DiagnosticosIndexRoute: DiagnosticosIndexRoute,
  DiagnosticosClientesClienteIdRoute: DiagnosticosClientesClienteIdRoute,
  DiagnosticosEditorDiagnosticoIdRoute: DiagnosticosEditorDiagnosticoIdRoute,
}

const DiagnosticosRouteWithChildren = DiagnosticosRoute._addFileChildren(
  DiagnosticosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgendarRoute: AgendarRouteWithChildren,
  AtendimentosRoute: AtendimentosRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosRoute: CustosRoute,
  DiagnosticosRoute: DiagnosticosRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SiteRoute: SiteRoute,
  UsuariosRoute: UsuariosRoute,
  PdfTokenRoute: PdfTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
