/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarDateRouteImport } from './routes/agendar.$date'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarDateRoute = AgendarDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => AgendarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/atendimentos': typeof AtendimentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/login': typeof LoginRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/usuarios': typeof UsuariosRoute
  '/agendar/$date': typeof AgendarDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/atendimentos': typeof AtendimentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/login': typeof LoginRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/usuarios': typeof UsuariosRoute
  '/agendar/$date': typeof AgendarDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/atendimentos': typeof AtendimentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/login': typeof LoginRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/usuarios': typeof UsuariosRoute
  '/agendar/$date': typeof AgendarDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/atendimentos'
    | '/clientes'
    | '/configuracoes'
    | '/custos'
    | '/login'
    | '/procedimentos'
    | '/usuarios'
    | '/agendar/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/atendimentos'
    | '/clientes'
    | '/configuracoes'
    | '/custos'
    | '/login'
    | '/procedimentos'
    | '/usuarios'
    | '/agendar/$date'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agendar'
    | '/atendimentos'
    | '/clientes'
    | '/configuracoes'
    | '/custos'
    | '/login'
    | '/procedimentos'
    | '/usuarios'
    | '/agendar/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgendarRoute: typeof AgendarRouteWithChildren
  AtendimentosRoute: typeof AtendimentosRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosRoute: typeof CustosRoute
  LoginRoute: typeof LoginRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$date': {
      id: '/agendar/$date'
      path: '/$date'
      fullPath: '/agendar/$date'
      preLoaderRoute: typeof AgendarDateRouteImport
      parentRoute: typeof AgendarRoute
    }
  }
}

interface AgendarRouteChildren {
  AgendarDateRoute: typeof AgendarDateRoute
}

const AgendarRouteChildren: AgendarRouteChildren = {
  AgendarDateRoute: AgendarDateRoute,
}

const AgendarRouteWithChildren =
  AgendarRoute._addFileChildren(AgendarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgendarRoute: AgendarRouteWithChildren,
  AtendimentosRoute: AtendimentosRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosRoute: CustosRoute,
  LoginRoute: LoginRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
